# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f8b72dfeaaf2508a0409e1f12268c26b4fccce829ae1cb0d254806aec345963179f0a0997acf4b9f194d6b3d593e7b22e57d1ba4d36dfeb1e5697e53f4a274d1

test:
  secret_key_base: 7a46e4ccb8781488130ae27d906959b0ab1e1a097db07d9c40cf79619647627dec9187272df25fb3a736a84ee37af2a8729c1f9abf4c4029102f20307908c8fb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
